services:
  web-app-123:
    container_name: web-app-node-123
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - "3100:3000"
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
