services:
  web-app:
    container_name: web-app
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    stdin_open: true
    tty: true
