openapi: 3.1.0
info:
  title: "Job Vacancy API | Get Vacancy"
  version: "1.0.0"
  description: |
    This API endpoint allows clients to retrieve a job vacancy by its unique identifier. It returns the vacancy details, including title, company, description, location, and posted date.

paths:
  /v1/vacancies/{id}:
    get:
      summary: "Retrieve Job Vacancy"
      description: |
        Retrieves the details of a specific job vacancy by its unique ID. The client must provide the ID of the vacancy.
      operationId: "getVacancy"
      tags:
        - "Vacancies"
      parameters:
        - name: id
          in: path
          required: true
          description: "The unique identifier of the job vacancy to retrieve"
          schema:
            type: integer
            example: 123
      responses:
        "200":
          description: "Job vacancy retrieved successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetVacancyResponse"
        "404":
          description: "Not Found - Vacancy with the specified ID was not found"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "Error message indicating vacancy not found"
        "500":
          description: "Internal Server Error - Unexpected server error occurred."
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: "Error message"

components:
  schemas:
    GetVacancyResponse:
      type: object
      properties:
        id:
          type: integer
          description: "The unique identifier of the job vacancy"
          example: 123
        title:
          type: string
          description: "The title of the job vacancy"
          example: "Software Engineer"
        company:
          type: string
          description: "The name of the company offering the job"
          example: "Tech Innovators Ltd."
        description:
          type: string
          description: "A description of the job responsibilities and requirements"
          example: "Looking for an experienced software engineer with expertise in Go and cloud infrastructure."
        posted_at:
          type: string
          format: date
          description: "The timestamp when the job was posted"
          example: "2024-11-12"
        location:
          type: string
          description: "The location of the job position"
          example: "San Francisco, CA"
      example:
        id: 123
        title: "Software Engineer"
        company: "Tech Innovators Ltd."
        description: "Looking for an experienced software engineer with expertise in Go and cloud infrastructure."
        posted_at: "2024-11-12"
        location: "San Francisco, CA"
