name: Integration Tests and Linters

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Allows manual triggering

jobs:
  run_tests_and_linters:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run Docker Compose
        run: docker-compose -f web-app-test.yml up -d

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until docker exec pulse_db_test pg_isready -U user_test; do
            echo "Waiting for PostgreSQL..."
            sleep 5
          done
          echo "PostgreSQL is ready."

      - name: Wait for Database Migrations to Complete
        run: |
          echo "Waiting for database migrations to complete..."
          until [ "$(docker inspect -f {{.State.Running}} pulse_db_migration_test)" == "false" ]; do
            echo "Waiting for migrations..."
            sleep 5
          done
          echo "Migrations completed."

      - name: Wait for NATS to be ready
        run: |
          echo "Waiting for NATS to be ready..."
          until curl -s http://localhost:8222/ > /dev/null; do
            echo "Waiting for NATS..."
            sleep 5
          done
          echo "NATS is ready."

      - name: Test Database Connection
        run: |
          PGPASSWORD=pass_test psql -h localhost -U user_test -d pulse_finder_test -c '\dt'

      - name: Test NATS Connection
        run: |
          curl -s http://localhost:8222/ > /dev/null || echo "Failed to connect to NATS"

      - name: Run Linters
        working-directory: src/backend
        run: |
          make lint

      - name: Run Integration Tests
        working-directory: src/backend
        run: |
          make test/integration

      - name: Capture PostgreSQL logs
        if: always()
        run: docker logs pulse_db_test

      - name: Capture NATS logs
        if: always()
        run: docker logs pulse_nats_test

      - name: Capture Migration Logs
        if: always()
        run: docker logs pulse_db_migration_test

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose -f web-app-test.yml down
