name: Integration Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Allows manual triggering

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run Docker Compose
        run: docker-compose -f web-app-test.yml up -d

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to be ready..."
          until docker exec pulse_db_test pg_isready -U user_test; do
            echo "Waiting for PostgreSQL..."
            sleep 5
          done
          echo "PostgreSQL is ready."

      - name: Wait for Database Migrations to Complete
        run: |
          echo "Waiting for database migrations to complete..."
          until [ "$(docker inspect -f {{.State.Running}} pulse_db_migration_test)" == "false" ]; do
            echo "Waiting for migrations..."
            sleep 5
          done
          echo "Migrations completed."

      - name: Wait for NATS to be ready
        run: |
          echo "Waiting for NATS to be ready..."
          until curl -s http://localhost:8222/ > /dev/null; do
            echo "Waiting for NATS..."
            sleep 5
          done
          echo "NATS is ready."

      - name: Run Integration Tests
        working-directory: src/backend
        run: |
          DB_DSN=postgres://user_test:pass_test@localhost:5432/pulse_finder_test?sslmode=disable \
          NATS_URL=nats://localhost:4222 \
          make test/integration/no-cache

      - name: Capture PostgreSQL logs if tests fail
        if: failure()
        run: docker logs pulse_db_test

      - name: Capture NATS logs if tests fail
        if: failure()
        run: docker logs pulse_nats_test

      - name: Capture Migration Logs if Tests Fail
        if: failure()
        run: docker logs pulse_db_migration_test

      - name: Tear down Docker Compose
        if: always()
        run: docker-compose -f web-app-test.yml down
