services:
  aws-cli:
    container_name: pulse_aws_cli
    image: amazon/aws-cli:latest
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      pulse_aws_cli_network:
        ipv4_address: 195.45.0.5
    volumes:
      - pulse_aws_cli:/root/.aws

  terraform:
    image: hashicorp/terraform:latest
    container_name: pulse_terraform
    volumes:
      - pulse_aws_cli:/root/.aws
      - ./terraform:/workspace
    working_dir: /workspace
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      pulse_aws_cli_network:
        ipv4_address: 195.45.0.7
    environment:
      - TF_LOG=TRACE

networks:
  pulse_aws_cli_network:
    ipam:
      driver: default
      config:
        - subnet: 195.45.0.0/16

volumes:
  pulse_aws_cli: